In [1]:
import cv2
import numpy as np
from numpy.lib.shape_base import split
from scipy.special import comb

In [14]:
arr = np.zeros((240*5,240*5,3),dtype=np.uint8)

pts = np.array([[0,0],[140,0],[0,140],[240,240]])

n = len(pts) - 1
split = 100 

w = np.ones((split+1,n+1))

t = np.linspace(0, 1, split+1)
tprod = np.ones(t.shape)
for i in range(n+1):
    w[:,i] *= tprod
    tprod *= t
    
talt = 1-t
tprod = np.ones(t.shape)
for i in range(n+1):
    w[:,n-i] *= tprod
    tprod *= talt

b = comb(n, np.arange(0,n+1,1,dtype=np.uint32))
for i in range(n+1):
    w[:,i] *= b[i]
print(w)

line = np.dot(w, pts)
# print(line.astype(np.uint32))
arr = cv2.polylines(arr, [line.astype(np.int32)],False, (255,255,255), 0)
# print(arr)
cv2.imshow("",arr)
if cv2.waitKey(0):
    cv2.destroyAllWindows()

[[1.00000e+00 0.00000e+00 0.00000e+00 0.00000e+00]
 [9.70299e-01 2.94030e-02 2.97000e-04 1.00000e-06]
 [9.41192e-01 5.76240e-02 1.17600e-03 8.00000e-06]
 [9.12673e-01 8.46810e-02 2.61900e-03 2.70000e-05]
 [8.84736e-01 1.10592e-01 4.60800e-03 6.40000e-05]
 [8.57375e-01 1.35375e-01 7.12500e-03 1.25000e-04]
 [8.30584e-01 1.59048e-01 1.01520e-02 2.16000e-04]
 [8.04357e-01 1.81629e-01 1.36710e-02 3.43000e-04]
 [7.78688e-01 2.03136e-01 1.76640e-02 5.12000e-04]
 [7.53571e-01 2.23587e-01 2.21130e-02 7.29000e-04]
 [7.29000e-01 2.43000e-01 2.70000e-02 1.00000e-03]
 [7.04969e-01 2.61393e-01 3.23070e-02 1.33100e-03]
 [6.81472e-01 2.78784e-01 3.80160e-02 1.72800e-03]
 [6.58503e-01 2.95191e-01 4.41090e-02 2.19700e-03]
 [6.36056e-01 3.10632e-01 5.05680e-02 2.74400e-03]
 [6.14125e-01 3.25125e-01 5.73750e-02 3.37500e-03]
 [5.92704e-01 3.38688e-01 6.45120e-02 4.09600e-03]
 [5.71787e-01 3.51339e-01 7.19610e-02 4.91300e-03]
 [5.51368e-01 3.63096e-01 7.97040e-02 5.83200e-03]
 [5.31441e-01 3.73977e-01 8.772

In [ ]:
weights = {}

pts = np.array([[0,0],[240,0],[240,240],[240,240]])

n = len(pts) - 1
if weights.get((n,split)) == None:
    weights[(n,split)] = genWeights(n,split)
print("?")
line = np.dot(weights[(n,split)], pts).astype(np.int32)

arr = np.zeros((240*5,240*5,3),dtype=np.uint8)
arr = cv2.polylines(arr, [line],False, (255,255,255), 0)
cv2.imshow("",arr)
if cv2.waitKey(0):
    cv2.destroyAllWindows()

In [16]:
def genWeights(n,split=100):
    w = np.ones((split+1,n+1))
    t = np.linspace(0, 1, split+1)
    tprod = np.ones(t.shape)
    for i in range(n+1):
        w[:,i] *= tprod
        tprod *= t
    tprod = np.ones(t.shape)
    for i in range(n+1):
        w[:,n-i] *= tprod
        tprod *= 1-t
    b = comb(n, np.arange(0,n+1,1,dtype=np.uint32))
    for i in range(n+1):
        w[:,i] *= b[i]
    return w